spring:
jpa:
  properties:
    hibernate:
      format_sql: true
      generate_statistics: true # 여러 통계정보 출력 - 캐시 적용 여부 확인(개발 환경에서만 적용)

      cache:
        use_second_level_cache: true # 2차 캐시 활성화 - 엔티티 캐시 & 컬렉션 캐시
        use_query_cache: true # 쿼리 캐시 활성화
        region:
          factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory # 2차 캐시 처리할 클래스 지정

    javax:
      persistence:
        sharedCache:
          mode: ENABLE_SELECTIVE # @Cacheable을 붙힌 엔티티에만 적용
